### ISSUE TITLE
Worker options

### ISSUE THREAD

**Issue by AlexandreDecollas** [xdave/bull-mq-transport#2]
Hi! 

I'm currently trying to use your lib, and it seems that the worker options are not transmitted to the factory. Could you please review a small change I did to do so it allows to use the full worker options and I saw that this is in your todo list :) ? 
I don't have the writes to push on your repo, so it was only possible to commit in local. May I ask you to allow me to push on a secondary branch please, and then review the corresponding PR?

Best regards

A.D.

**Comment by AlexandreDecollas** [comment]
And so at the end I red on gituhub doc how to do it without the rights :) I link the PR

**Comment by AlexandreDecollas** [comment]
linked PR : https://github.com/xdave/bull-mq-transport/pull/3

**Comment by xdave** [comment]
@AlexandreDecollas  merged your pr and published 3.0.1
